// Code generated by "stringer -type=Column -trimprefix Column -linecomment"; DO NOT EDIT.

package tool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Module-0]
	_ = x[Version-1]
	_ = x[Package-2]
	_ = x[Via-3]
}

const _Column_name = "ModuleVersionImported packageVia (at least...)"

var _Column_index = [...]uint8{0, 6, 13, 29, 46}

func (i Column) String() string {
	if i < 0 || i >= Column(len(_Column_index)-1) {
		return "Column(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Column_name[_Column_index[i]:_Column_index[i+1]]
}
