name: Tests
permissions:
  contents: read
on:
  schedule:
    - cron: "42 6 * * MON"
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and run ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ "stable", "oldstable" ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: go generate returns nothing
        run: |
          DELTA=$(go generate ./...) || exit 1
          echo $DELTA
          test -z "$DELTA"

      - name: Build
        run: go build .

      - name: Self-check
        run: ./go-pvd . | tee report.txt

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: PVD Report go-${{ matrix.go-version }}
          path: report.txt
